### ISSUE TITLE
Cryptographically insecure RSA implementation

### ISSUE THREAD

**Issue by HenkPoley** [dp-ifacesoft/IcEngine#1]
This file contains a small list of small primes, that is easily crackable and thus insecure: https://github.com/dp-ifacesoft/IcEngine/blob/54436374c0c5262b80130e8cdf6a28c065c6124a/Class/Crypt/AES.php#L14

Issue is similar as: https://twitter.com/voodooKobra/status/663581509069242368

The small prime numbers are picked and used to generate a small insecure key at line 97 and 100.

**Comment by dp-ifacesoft** [comment]
Thank you, but the project is already obsolete.

**Comment by HenkPoley** [comment]
I understand that. The trouble is that people will find this implementation and try to use it.

E.g.: http://stackoverflow.com/questions/33593140/how-to-generate-signature-and-keys-in-codeigniter-rsa-library
